<template>
  <ul
    class="
      hidden
      static
      font-sourcecode
      text-sm
      md:flex
      justify-start
      items-center
    "
  >
    <li>
      <nuxt-link
        to="/#about"
        class="
          px-4
          py-2
          text-center
          block
          w-full
          transition
          hover:text-blue-500
          dark:hover:text-cyan-400
          focus:text-blue-500
          dark:focus:text-cyan-400
        "
        >About Us</nuxt-link
      >
    </li>
    <li>
      <nuxt-link
        to="/#buy"
        class="
          px-4
          py-2
          text-center
          block
          w-full
          transition
          hover:text-blue-500
          dark:hover:text-cyan-400
          focus:text-blue-500
          dark:focus:text-cyan-400
        "
        >Buy</nuxt-link
      >
    </li>
    <li>
      <nuxt-link
        to="/#sell"
        class="
          px-4
          py-2
          text-center
          block
          w-full
          transition
          hover:text-blue-500
          dark:hover:text-cyan-400
          focus:text-blue-500
          dark:focus:text-cyan-400
        "
        >Sell</nuxt-link
      >
    </li>
    <li>
      <nuxt-link
        to="/#partner"
        class="
          px-4
          py-2
          text-center
          block
          w-full
          transition
          hover:text-blue-500
          dark:hover:text-cyan-400
          focus:text-blue-500
          dark:focus:text-cyan-400
        "
        >Partner</nuxt-link
      >
    </li>
    <li>
      <nuxt-link
        to="/#farms"
        class="
          px-4
          py-2
          text-center
          block
          w-full
          transition
          hover:text-blue-500
          dark:hover:text-cyan-400
          focus:text-blue-500
          dark:focus:text-cyan-400
        "
        >Our Farms</nuxt-link
      >
    </li>
  </ul>
</template>

<script>
export default {
  name: 'NavMenu'
};
</script>
